power: qpnp-fg-gen3: fix -Wsizeof-array-div Fixes the warning: drivers/power/supply/qcom/supply/qcom/qpnp-fg-gen3.c:2555:32: error: expression does not compute the number of elements in this array; element type is 'u16' (aka 'unsigned short'), not 'u8 *' (aka 'unsigned char *') [-Werror,-Wsizeof-array-div] sizeof(chip->cyc_ctr.count) / sizeof(u8 *),        ~~~~~~~~~~~~~~~~~~~  ^        Seen when upgrading the kernel toolchain to clang-r377782b.
       fg_sram_write() expects the `len` parameter to be a number of bytes to
       write. `chip->cyc_ctr.count` is declared as a `u16[]`.

       Bug: 149786337
       Signed-off-by: Nick Desaulniers <ndesaulniers@google.com>
       Change-Id: Ib184079e92f6c51256ee1fa1ba4c802b15fdf11f